### ISSUE TITLE
Appdaemon is not compatible with Python 3.9

### ISSUE THREAD

**Issue by chbndrhnns** [AppDaemon/appdaemon#1064]
Running it in a 3.9 venv gives me this error:

```
Traceback (most recent call last):
  File "/Users/jo/.virtualenvs/appdaemon-MLpxRBnC/bin/appdaemon", line 5, in <module>
    from appdaemon.__main__ import main
  File "/Users/jo/.virtualenvs/appdaemon-MLpxRBnC/lib/python3.9/site-packages/appdaemon/__main__.py", line 23, in <module>
    import appdaemon.http as adhttp
  File "/Users/jo/.virtualenvs/appdaemon-MLpxRBnC/lib/python3.9/site-packages/appdaemon/http.py", line 9, in <module>
    import feedparser
  File "/Users/jo/.virtualenvs/appdaemon-MLpxRBnC/lib/python3.9/site-packages/feedparser.py", line 93, in <module>
    _base64decode = getattr(base64, 'decodebytes', base64.decodestring)
AttributeError: module 'base64' has no attribute 'decodestring'
```

**Comment by benniju** [comment]
I have exactly the same Problem running with pyenv on Linux with a Raspberry Pi:

```
Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/appdaemon/bin/appdaemon", line 5, in <module>
    from appdaemon.__main__ import main
  File "/home/homeassistant/.pyenv/versions/3.9.0/envs/appdaemon/lib/python3.9/site-packages/appdaemon/__main__.py", line 23, in <module>
    import appdaemon.http as adhttp
  File "/home/homeassistant/.pyenv/versions/3.9.0/envs/appdaemon/lib/python3.9/site-packages/appdaemon/http.py", line 9, in <module>
    import feedparser
  File "/home/homeassistant/.pyenv/versions/3.9.0/envs/appdaemon/lib/python3.9/site-packages/feedparser.py", line 93, in <module>
    _base64decode = getattr(base64, 'decodebytes', base64.decodestring)
AttributeError: module 'base64' has no attribute 'decodestring'
```
I guess I will have to work with Python 3.8, which is annoying because Home-Assistant works on 3.9 (of course I have a seperate venv)

**Comment by ReneTode** [comment]
its always difficult to keep up with other programs.
HA has a ton of (partly paid) developers, AD only has a few.
HA decided that users need to upgrade to python 3.8, while AD still is running on python 3.6 (which is very fine for synology users)

in venv or in docker there is no problem with using python 3.8, and as long as HA still supports 3.8 the addon also can work with 3.8

**Comment by tirkarthi** [comment]
This was fixed in feedparser with https://github.com/kurtmckee/feedparser/pull/206 and available in feedparser 6.0.0 and above as per commit https://github.com/kurtmckee/feedparser/commit/828a7334c0fb73c3499f46886aa995a0ec347143

**Comment by xumxum** [comment]
I tried aplying manually the fix to feedparser, to use the decodebytes, but still doesn't run with python 3.9, there is no error printed, it just exists..Tried running it with python -v (verbose) but still I could not see any immediate errors..
After installed python3.8 along my python3.9. and managed to get pip somehow going..i was able to get appdaemon running again.
[appdaemon_python3_9.log](https://github.com/AppDaemon/appdaemon/files/5653359/appdaemon_python3_9.log)

**Comment by daringer** [comment]
had the same issue, quickfix to be found inside the PR

**Comment by acockburn** [comment]
AD is now happily running on 3.9 - closing.

**Comment by bagelos** [comment]
Hi - is are there specific instructions to resole app-daemon running with python 3.9?

**Comment by acockburn** [comment]
Currently you will need to run the dev branch to pick this up - when 4.1.0 is released it will be included - no firm date for 4.1.0 yet but soon, maybe this weekend.

**Comment by bagelos** [comment]
Aha - thanks Andrew.  For now, reverted to a 3.8 venv and all working ok.  I'll keep an eye out for 4.1.0.  Cheers.
