### ISSUE TITLE
Please update dependencies; cchardet is abandoned; build on Python 3.11 currently impossible

### ISSUE THREAD

**Issue by HWiese1980** [AppDaemon/appdaemon#1651]
### Original issue 
aiohttp 3.8.1 has issues with Python 3.11, cannot be built. aiohttp 3.8.2 works. 

Building aiohttp 3.8.1 with Python 3.11 results in 

```shell
yarl/_quoting_c.c:198:12: fatal error: 'longintrepr.h' file not found
        #include "longintrepr.h"
                 ^~~~~~~~~~~~~~~
```

### Update

`cchardet` is also affected by this error. And contrary to aiohttp it cannot be updated beyond its current state as it seems to be abandoned.

### Update 2

https://github.com/Ousret/charset_normalizer is named as alternative

**Comment by frenck** [comment]
Please upgrade beyond that... 3.8.2 has memory leaks when used in conjunction with SSL

**Comment by HWiese1980** [comment]
`cchardet 2.1.7` has the same issue; unfortunately it's the latest version available

**Comment by acockburn** [comment]
Dev currently has aiohttp==3.8.4, I'll be putting out a release soon.

AFAIK, cchardet isn't a specific dependency but I'll check into why we need it and ensure the next release supports python 3.11.

**Comment by HWiese1980** [comment]
Awesome! For a local install that I needed for code completion in Visual Studio Code, it was already enough to remove cchardet from the `requirements.txt`. But I don't know if `appdaemon` would actually run like that. Haven't tested it.

**Comment by acockburn** [comment]
Yep – it seems to have been an orphaned dependency, or more likely I added it because aiohttp used it. I have now removed it from the dependencies and all seems fine. I also ran some tests in python 3.11 just to be on the safe side. I didn’t build anything for this, just used prebuilt packages that pip supplied. The next release of AD later today will have this fix, so I’ll close the issue – thanks for the heads up, and let me know if you still have issues.
