### ISSUE TITLE
entity_state has "undefined" instead of entity named sub-objects in OnStateAvailable Callback.

### ISSUE THREAD

**Issue by n8hjp** [AppDaemon/appdaemon#1031]
**Problem/Motivation**

My custom Widgets no longer work in 4.0.5.  (Sorry I am not sure when it last worked, I hadn't upgraded for a while...)

**Expected behavior**

In the past the entity_state object had sub-objects with the entity name. Now in the OnStateAvailable call it is named "undefined." In the OnStateUpdate, there is one object with the proper name, but also has an additional object with the name "undefined." (This really isn't a problem, but is different behavior than before.)   I highlighted in bold the examples from the JS console log.

**Actual behavior**

Here is the specific example of the self object during these calls:

OnStateAvailable:  (full details are attached)

entity_state: Object input_text.condition_alarm: Object
**undefined: Object**
attributes: {editable: true, friendly_name: "Alarm Condition", max: 100, min: 0, mode: "text", …}
context: {id: "8dc732a1ea1d11ea95ca0bb8702f7428", parent_id: "8dc13de0ea1d11eab508bdfd74e861f9", user_id: null}
entity_id: "input_text.condition_alarm"
last_changed: "2020-08-29T17:32:04.221198+00:00"
last_updated: "2020-08-29T17:32:04.221198+00:00"
state: "Green"

![Screen Shot 2020-08-30 at 3 26 00 PM](https://user-images.githubusercontent.com/63569764/91667798-26510900-ead5-11ea-912a-b60819dd3e60.png)

OnStateUpdate: (full details are attached)

entity_state: Object
input_text.condition_alarm: Object
attributes: {editable: true, min: 0, max: 100, pattern: null, mode: "text", …}
context: {id: "0bcfc9cfea1f11eaaa5b91aa09726c57", parent_id: "0bc73117ea1f11ea920fe9ce64514d2c", user_id: null}
entity_id: "input_text.condition_alarm"
last_changed: "2020-08-29T17:42:45.192048+00:00"
last_updated: "2020-08-29T17:42:45.192048+00:00"
state: "Green".
**undefined: Object**
attributes: {editable: true, friendly_name: "Alarm Condition", max: 100, min: 0, mode: "text", …}
context: {id: "8dc732a1ea1d11ea95ca0bb8702f7428", parent_id: "8dc13de0ea1d11eab508bdfd74e861f9", user_id: null}
entity_id: "input_text.condition_alarm"
last_changed: "2020-08-29T17:32:04.221198+00:00"
last_updated: "2020-08-29T17:32:04.221198+00:00"
state: "Green"

![Screen Shot 2020-08-30 at 3 20 06 PM](https://user-images.githubusercontent.com/63569764/91667681-58ae3680-ead4-11ea-83b8-531ca97418f2.png)

**Steps to reproduce**

I have some poorly written rather complex widgets (As most of my programming, I really mean to clean up the code, but it has been working...). The most complex one watch 5 different entities and present a widget with probably all too much information in it :-).   I picked a simple one for this example.

I am running on Hassio, Supervisor versos 235 HassOS 4.12 using the AppDaemon Add-On.    I have removed and reinstalled AppDaemon to see if this would resolve the issue.

**Comment by ReneTode** [comment]
its very hard to debug a widget that we dont know.
without the widget code i can hardly tell what is wrong with it.

i expect you upgraded from AD 3 to AD 4, and there are a lot of changes on the background there.
but the most common problem from AD 3 custom widgets is that they have in the yaml files things like:
```
entity_id: {{entity_id}}
```

and because of changes in the yaml interpreter that now needs to be
```
entity_id: "{{entity_id}}"
```

if that is not your problem you will need to share your widget files.

1 big change that took place that effects js code is that dashboard now only sees state changes from  entities that are defined in the JS.
in AD 3 dashboard got every state change.

**Comment by n8hjp** [comment]
Thanks, I assume I was taking some liberties with my coding that were working, but probably shouldn't have.    I have been running AD4 for a while, but when I removed it and reinstalled it I had to clear up a few things that I had miss, and must have been working because of something being leftover...    Mostly to do with Authentication with HA.

**Comment by n8hjp** [comment]
Thanks for the quick response.     I had done the AD3=>AD4 update a while back, but when I wiped it and reinstalled it didn't work until I change a few things, so there was some leftover baggage somewhere.

**Comment by ReneTode** [comment]
your welcome and the best place to ask is on discord:
https://discord.gg/wrdqRK6

**Comment by n8hjp** [comment]
Just to close this out.    Since the widget documentation doesn't refer to entity_state, only the state object.   I assume that I shouldn't have counted on the self.entity_state objects being up to date.   While in the past they seemed to up to date and consistent, they are now very inconsistent.      If rewrote my widgets to look at the state object instead and they work good, even better than what I was doing before.
